#!/usr/bin/env python3
"""Rebuild the embedded demo assets from the reviewed source commit.

Usage:
  python3 template4datatug/generate_demo_template.py --source-repo /path/to/datatug-demo-project

Update SOURCE_COMMIT only when refreshing the template from a reviewed merge.
The archive contains tracked regular files from that commit only; tar metadata
and gzip timestamps are normalized for reproducible output.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import json
import subprocess
import tarfile
from pathlib import Path


SOURCE = "datatug/datatug-demo-project"
TEMPLATE_ID = "demo-project-1"
SOURCE_COMMIT = "436350d41371103be11144ffa346c605f85e1342"
MAX_TEMPLATE_FILE = 1 << 20


def git(repo: Path, *args: str) -> bytes:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    ).stdout


def build(repo: Path) -> None:
    resolved = git(repo, "rev-parse", "--verify", f"{SOURCE_COMMIT}^{{commit}}").decode().strip()
    if resolved != SOURCE_COMMIT:
        raise SystemExit(f"source commit resolved unexpectedly: {resolved}")

    records = git(repo, "ls-tree", "-r", "-z", "--full-tree", SOURCE_COMMIT, "--", TEMPLATE_ID)
    files: list[tuple[str, bytes]] = []
    for record in records.split(b"\0"):
        if not record:
            continue
        header, raw_path = record.split(b"\t", 1)
        mode, kind, oid = header.decode("ascii").split()
        path = raw_path.decode("utf-8")
        if mode != "100644" or kind != "blob" or not path.startswith(TEMPLATE_ID + "/"):
            raise SystemExit(f"unsupported source entry: {mode} {kind} {path!r}")
        if "\\" in path or "\n" in path or "\r" in path or ".." in path.split("/"):
            raise SystemExit(f"unsafe source path: {path!r}")
        content = git(repo, "cat-file", "blob", oid)
        if len(content) > MAX_TEMPLATE_FILE:
            raise SystemExit(f"source file exceeds {MAX_TEMPLATE_FILE} bytes: {path}")
        files.append((path, content))

    files.sort(key=lambda item: item[0])
    if not files:
        raise SystemExit("source template is empty")

    manifest = {
        "source": SOURCE,
        "templateID": TEMPLATE_ID,
        "commit": SOURCE_COMMIT,
        "files": [
            {
                "path": path,
                "mode": "100644",
                "size": len(content),
                "sha256": hashlib.sha256(content).hexdigest(),
            }
            for path, content in files
        ],
    }
    manifest_bytes = (json.dumps(manifest, sort_keys=True, separators=(",", ":")) + "\n").encode()

    archive_buffer = io.BytesIO()
    with gzip.GzipFile(fileobj=archive_buffer, mode="wb", filename="", mtime=0, compresslevel=9) as gz:
        with tarfile.open(fileobj=gz, mode="w", format=tarfile.PAX_FORMAT) as archive:
            for path, content in files:
                entry = tarfile.TarInfo(path)
                entry.type = tarfile.REGTYPE
                entry.mode = 0o644
                entry.size = len(content)
                entry.mtime = 0
                entry.uid = 0
                entry.gid = 0
                entry.uname = ""
                entry.gname = ""
                archive.addfile(entry, io.BytesIO(content))
    archive_bytes = archive_buffer.getvalue()

    total_bytes = sum(len(content) for _, content in files)
    archive_sha = hashlib.sha256(archive_bytes).hexdigest()
    manifest_sha = hashlib.sha256(manifest_bytes).hexdigest()
    constants = f'''// Code generated by generate_demo_template.py; DO NOT EDIT.
package template4datatug

const (
	DemoProjectCommit = "{SOURCE_COMMIT}"
	// DemoProjectFileCount is the exact number of regular files in this pinned template.
	DemoProjectFileCount = {len(files)}
	archiveSHA256 = "{archive_sha}"
	manifestSHA256 = "{manifest_sha}"
	maxTemplateFiles = DemoProjectFileCount
	maxTemplateBytes = {total_bytes}
)
'''.encode()

    asset_dir = Path(__file__).parent / "assets"
    (asset_dir / "demo-project-1.tar.gz").write_bytes(archive_bytes)
    (asset_dir / "demo-project-1-manifest.json").write_bytes(manifest_bytes)
    generated_go = Path(__file__).parent / "template_assets_generated.go"
    generated_go.write_bytes(constants)
    subprocess.run(["gofmt", "-w", str(generated_go)], check=True)
    print(f"source={SOURCE}@{SOURCE_COMMIT} files={len(files)} bytes={total_bytes}")
    print(f"archive_sha256={archive_sha} manifest_sha256={manifest_sha}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-repo", type=Path, required=True)
    args = parser.parse_args()
    build(args.source_repo.resolve())


if __name__ == "__main__":
    main()
