// Code generated by generate_demo_template.py; DO NOT EDIT.
package template4datatug

const (
	DemoProjectCommit = "d32475de887f65fc18276fae2c8c7a6af5b3fcf6"
	// DemoProjectFileCount is the exact number of regular files in this pinned template.
	DemoProjectFileCount = 637
	archiveSHA256        = "e14fb481f7bb18ad87b973c600c1cf0cfb5d367a45352c3cabc2fe7bd8f7de56"
	manifestSHA256       = "1bfc3616ff939366aceccf079918819f4f69b556ae15ba77958a596520a45cc3"
	maxTemplateFiles     = DemoProjectFileCount
	maxTemplateBytes     = 284267
)
