// Code generated by generate_demo_template.py; DO NOT EDIT.
package template4datatug

const (
	DemoProjectCommit = "436350d41371103be11144ffa346c605f85e1342"
	// DemoProjectFileCount is the exact number of regular files in this pinned template.
	DemoProjectFileCount = 637
	archiveSHA256        = "acb6ee2767a4e5ca62596d2212d7fbba5515a74edaad47c72e60df9cfe6a0c23"
	manifestSHA256       = "c9bb528ca9088e684defdb7a5162d0fa9e17fe6480bb1afb0395d05a798616ae"
	maxTemplateFiles     = DemoProjectFileCount
	maxTemplateBytes     = 284565
)
